# Generated by Django 3.1a1 on 2020-07-07 18:52

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reg_SecurityQuestion', models.CharField(choices=[('q1', "What is your first pet's name?"), ('q2', 'Who is your favorite teacher?'), ('q3', 'What is the name of the town where you were born?'), ('q4', 'What elementary school did you attend?')], default='q1', max_length=100)),
                ('reg_SecurityAnswer', models.CharField(max_length=100)),
                ('reg_ReferalId', models.CharField(max_length=50)),
                ('reg_CustomerId', models.CharField(max_length=50)),
                ('reg_Gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('others', 'Others')], default='male', max_length=10)),
                ('reg_MainBalance', models.IntegerField(default=75)),
                ('reg_RewardsPoints', models.IntegerField(default=25)),
                ('reg_is_cancelled', models.BooleanField(default=False)),
                ('reg_is_revoked', models.BooleanField(default=False)),
                ('reg_profile_pic', models.ImageField(default='./static/registration/images/default.jpg', upload_to='')),
                ('reg_CountryCode', models.CharField(choices=[('india', '+91'), ('usa', '+1')], default='india', max_length=5)),
                ('reg_MobileNumber', models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '9999999999'. Up to 15 digits allowed.", regex='^\\d{9,15}$')])),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
