# Generated by Django 3.1a1 on 2020-07-08 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='reg_CountryCode',
            field=models.CharField(choices=[('+91', '+91(India)'), ('+1', '+1(USA)')], default='+91', max_length=5),
        ),
        migrations.AlterField(
            model_name='registration',
            name='reg_CustomerId',
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='registration',
            name='reg_ReferalId',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='registration',
            name='reg_SecurityQuestion',
            field=models.CharField(choices=[("What is your first pet's name?", "What is your first pet's name?"), ('Who is your favorite teacher?', 'Who is your favorite teacher?'), ('What is the name of the town where you were born?', 'What is the name of the town where you were born?'), ('What elementary school did you attend?', 'What elementary school did you attend?')], default="What is your first pet's name?", max_length=100),
        ),
    ]
