# Generated by Django 3.1a1 on 2020-07-08 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0002_auto_20200708_0738'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='reg_CustomerId',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='registration',
            name='reg_ReferalId',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
