# Generated by Django 3.1a1 on 2020-07-08 03:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0004_auto_20200708_0844'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registration',
            old_name='user',
            new_name='reg_user',
        ),
    ]
